// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A4VSystemTimeout.proto

#ifndef PROTOBUF_A4VSystemTimeout_2eproto__INCLUDED
#define PROTOBUF_A4VSystemTimeout_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_A4VSystemTimeout_2eproto();
void protobuf_AssignDesc_A4VSystemTimeout_2eproto();
void protobuf_ShutdownFile_A4VSystemTimeout_2eproto();

class systemtimeoutcontrol;

// ===================================================================

class systemtimeoutcontrol : public ::google::protobuf::Message {
 public:
  systemtimeoutcontrol();
  virtual ~systemtimeoutcontrol();
  
  systemtimeoutcontrol(const systemtimeoutcontrol& from);
  
  inline systemtimeoutcontrol& operator=(const systemtimeoutcontrol& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const systemtimeoutcontrol& default_instance();
  
  void Swap(systemtimeoutcontrol* other);
  
  // implements Message ----------------------------------------------
  
  systemtimeoutcontrol* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const systemtimeoutcontrol& from);
  void MergeFrom(const systemtimeoutcontrol& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool autopowerdown = 1;
  inline bool has_autopowerdown() const;
  inline void clear_autopowerdown();
  static const int kAutopowerdownFieldNumber = 1;
  inline bool autopowerdown() const;
  inline void set_autopowerdown(bool value);
  
  // optional bool screensaver = 2;
  inline bool has_screensaver() const;
  inline void clear_screensaver();
  static const int kScreensaverFieldNumber = 2;
  inline bool screensaver() const;
  inline void set_screensaver(bool value);
  
  // @@protoc_insertion_point(class_scope:systemtimeoutcontrol)
 private:
  inline void set_has_autopowerdown();
  inline void clear_has_autopowerdown();
  inline void set_has_screensaver();
  inline void clear_has_screensaver();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  bool autopowerdown_;
  bool screensaver_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_A4VSystemTimeout_2eproto();
  friend void protobuf_AssignDesc_A4VSystemTimeout_2eproto();
  friend void protobuf_ShutdownFile_A4VSystemTimeout_2eproto();
  
  void InitAsDefaultInstance();
  static systemtimeoutcontrol* default_instance_;
};
// ===================================================================


// ===================================================================

// systemtimeoutcontrol

// optional bool autopowerdown = 1;
inline bool systemtimeoutcontrol::has_autopowerdown() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void systemtimeoutcontrol::set_has_autopowerdown() {
  _has_bits_[0] |= 0x00000001u;
}
inline void systemtimeoutcontrol::clear_has_autopowerdown() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void systemtimeoutcontrol::clear_autopowerdown() {
  autopowerdown_ = false;
  clear_has_autopowerdown();
}
inline bool systemtimeoutcontrol::autopowerdown() const {
  return autopowerdown_;
}
inline void systemtimeoutcontrol::set_autopowerdown(bool value) {
  set_has_autopowerdown();
  autopowerdown_ = value;
}

// optional bool screensaver = 2;
inline bool systemtimeoutcontrol::has_screensaver() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void systemtimeoutcontrol::set_has_screensaver() {
  _has_bits_[0] |= 0x00000002u;
}
inline void systemtimeoutcontrol::clear_has_screensaver() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void systemtimeoutcontrol::clear_screensaver() {
  screensaver_ = false;
  clear_has_screensaver();
}
inline bool systemtimeoutcontrol::screensaver() const {
  return screensaver_;
}
inline void systemtimeoutcontrol::set_screensaver(bool value) {
  set_has_screensaver();
  screensaver_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_A4VSystemTimeout_2eproto__INCLUDED
