#ifndef __KEYACTION_H__
#define __KEYACTION_H__

typedef enum 
{
    KEY_ACTION_0 = 9000,
    KEY_ACTION_1,
    KEY_ACTION_2,
    KEY_ACTION_3,
    KEY_ACTION_4,
    KEY_ACTION_5,
    KEY_ACTION_6,
    KEY_ACTION_7,
    KEY_ACTION_8,
    KEY_ACTION_9,
    KEY_ACTION_10,
    KEY_ACTION_12,
    KEY_ACTION_13,
    KEY_ACTION_14,
    KEY_ACTION_15
} KEY_EVENT;

#endif

