// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebServerMsgIds.proto

#ifndef PROTOBUF_WebServerMsgIds_2eproto__INCLUDED
#define PROTOBUF_WebServerMsgIds_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WebServerMsgIds_2eproto();
void protobuf_AssignDesc_WebServerMsgIds_2eproto();
void protobuf_ShutdownFile_WebServerMsgIds_2eproto();


enum WebServerMsgId {
  WEB_SERVER_MSG_ID_REGISTER = 0,
  WEB_SERVER_MSG_ID_MESSAGE = 10,
  WEB_SERVER_MSG_ID_MESSAGE_COMMAND = 11,
  WEB_SERVER_MSG_ID_MESSAGE_SEND_TO_ALL_WEBSOCKET_CLIENTS = 20,
  WEB_SERVER_MSG_ID_MESSAGE_SEND_TO_LISA_CLIENTS_IN_MY_ZONE = 30
};
bool WebServerMsgId_IsValid(int value);
const WebServerMsgId WebServerMsgId_MIN = WEB_SERVER_MSG_ID_REGISTER;
const WebServerMsgId WebServerMsgId_MAX = WEB_SERVER_MSG_ID_MESSAGE_SEND_TO_LISA_CLIENTS_IN_MY_ZONE;
const int WebServerMsgId_ARRAYSIZE = WebServerMsgId_MAX + 1;

const ::google::protobuf::EnumDescriptor* WebServerMsgId_descriptor();
inline const ::std::string& WebServerMsgId_Name(WebServerMsgId value) {
  return ::google::protobuf::internal::NameOfEnum(
    WebServerMsgId_descriptor(), value);
}
inline bool WebServerMsgId_Parse(
    const ::std::string& name, WebServerMsgId* value) {
  return ::google::protobuf::internal::ParseNamedEnum<WebServerMsgId>(
    WebServerMsgId_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< WebServerMsgId>() {
  return WebServerMsgId_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WebServerMsgIds_2eproto__INCLUDED
