#pragma once
#define DATA_COLLECTION_ACCESSORIES         "accessories-changed"
#define DATA_COLLECTION_EEDID               "eedid-changed"
#define DATA_COLLECTION_BASS                "bass-audio-parameters-changed"
#define DATA_COLLECTION_TREBLE              "treble-audio-parameters-changed"
#define DATA_COLLECTION_CENTER              "center-audio-parameters-changed"
#define DATA_COLLECTION_SURROUND            "surround-audio-parameters-changed"
#define DATA_COLLECTION_SURROUND_DELAY      "surrounddelay-audio-parameters-changed"
#define DATA_COLLECTION_GAIN_OFFSET         "gainoffset-audio-parameters-changed"
#define DATA_COLLECTION_AVSYNC              "avsync-audio-parameters-changed"
#define DATA_COLLECTION_SUBWOOFER_GAIN      "subwoofergain-audio-parameters-changed"
#define DATA_COLLECTION_CONTENT_TYPE        "contenttype-audio-parameters-changed"
#define DATA_COLLECTION_MODE                "mode-audio-parameters-changed"
#define DATA_COLLECTION_DUALMONO_SELECT     "dualmonoselect-audio-parameters-changed"
#define DATA_COLLECTION_EQSELECT            "eqselect-audio-parameters-changed"
#define DATA_COLLECTION_MOUNT_ORIENTATION   "mountorientation-audio-parameters-changed"
#define DATA_COLLECTION_SUBWOOFER_POLARITY  "subwooferpolarity-audio-parameters-changed"
