#!/bin/bash
#
# This script is invoke by systemd.
# See: /etc/systemd/system/bose.service
#
# This script's only purpose is for systemd to invoke the SoundTouch script.
# If you're thinking about having this script do something more, you're almost
# certainly wrong.
#

# Todo: Change egrep to jq query
# Status is Pending install Only if Status is ERROR / INPROGRESS Or 
# Atleast one status is In START when atleast one is COMPLETE   

# create swUpdateCache if not already exists
swUpCache=/opt/Bose/.swUpdateCache
if [ ! -d "$swUpCache" ]; then
    /opt/Bose/bin/pre_install
    mkdir -p $swUpCache
    /opt/Bose/bin/post_install

    mount --bind /opt/Bose/.swUpdateCache /opt/Bose/.swUpdateCache 
    mount -o remount -w /opt/Bose/.swUpdateCache /opt/Bose/.swUpdateCache 
fi

installPending=false
jq .SwUpComponents.elements[].status /mnt/nv/updateSwUpComponentStatus.dat > /tmp/status.txt
if egrep -q "STATUS_ERROR|STATUS_INPROGRESS" /tmp/status.txt; then
    echo "Install is pending - error / inprogress"
    installPending=true
else 
    if egrep -q "STATUS_START" /tmp/status.txt && egrep -q "STATUS_OK" /tmp/status.txt; then
        echo "Install is pending - one or more complete"
        installPending=true        
    fi
fi
if $installPending; then
    if [ -e /opt/Bose/.swUpdateCache/backup/install ]; then
        echo "Executing install from backup location"
        if [ -e /opt/Bose/.swUpdateCache/backup/unshare ]; then
            exec /opt/Bose/.swUpdateCache/backup/unshare -m /opt/Bose/.swUpdateCache/backup/install "$@"
        else
            exec /opt/Bose/.swUpdateCache/backup/install "$@"
        fi
    fi
    if [ -e /opt/Bose/bin/install ]; then
    	echo "Executing install from normal location"
        if [ -e /opt/Bose/update/bin/unshare ]; then
            exec /opt/Bose/update/bin/unshare -m /opt/Bose/bin/install "$@"
        else
            exec /opt/Bose/bin/install "$@"
        fi
    fi
    echo "Install is pending but running SoundTouch"
    exec /opt/Bose/bin/SoundTouch "$@"
else
    echo "Install is not pending"
    if [ -e /opt/Bose/bin/install ]; then
        /opt/Bose/bin/SoundTouch "$@" &
        if [ -e /opt/Bose/update/bin/unshare ]; then
            exec /opt/Bose/update/bin/unshare -m /opt/Bose/bin/install "$@" 
        else
            exec /opt/Bose/bin/install "$@" 
        fi
    else
       exec /opt/Bose/bin/SoundTouch "$@" 
    fi
fi

