#!/bin/bash
#
# This script is invoked from `/opt/Bose/bin/SoundTouch start` before starting
# the daemons to do any product/platform specific initialization.
#

if (( $# > 0 )); then
    echo >&2 "$0: unexpected argument '$1'"
    exit 1
fi

set_ap.sh
