#!/bin/sh
# Helper script for `/proc/sys/kernel/core_pattern`.
# Launched by the Linux kernel to store a core file.
# With no arguments, set the core_pattern.

PATH=/opt/Bose/bin:/bin:/usr/bin

if [ $# -eq 0 ]; then
    echo "|/opt/Bose/etc/store-core %p %e %s %t %E" \
         >/proc/sys/kernel/core_pattern
    # %p PID
    # %e task name or basename of executable (see prctl PR_SET_NAME)
    # %s number of signal causing dump
    # %t time of dump (POSIX time - seconds since 1970)
    # %E executable pathname (slashes/ changed to bangs!)
    exit
fi
pid=$1; shift
comm=$1; shift
sig=$1; shift
time=$1; shift
exe=$*

warn () {
    logger -s -t "store-core[$$]" -p warning "$*"
}

warn "pid=$pid, comm=$comm, sig=$sig, time=$time, exe=$exe"

commit=$(jq -r .abbrev_commit /opt/Bose/etc/BoseVersion.json) ||
    commit=unknown

core=/mnt/nv/BoseLog/core-$commit-${exe##*!}-$comm-$pid-$sig-$time.gz

clean_logs

warn "Creating core file '$core'..."
if gzip > "$core"; then
    warn "Creating core file...done"
else
    warn "Creating core file...failed"
fi
