////////////////////////////////////////////////////////////////////////////////
/// @file   ProductControllerStates.h
/// @brief  Definition of Product Controller Hsm state IDs. Both common and
///         product specific state Ids should be defined here.
///
/// Copyright 2017 Bose Corporation
////////////////////////////////////////////////////////////////////////////////

#pragma once

/// Important Note: HsmState framework reserves '0' as top state. DO NOT USE!

enum ProductControllerStates
{
    PRODUCT_CONTROLLER_STATE_BOOTING = 1,
    PRODUCT_CONTROLLER_STATE_REBOOTING,
    PRODUCT_CONTROLLER_STATE_SETUP,
    PRODUCT_CONTROLLER_STATE_CRITICAL_ERROR,
    PRODUCT_CONTROLLER_STATE_NETWORK_STANDBY_CONFIGURED,
    PRODUCT_CONTROLLER_STATE_NETWORK_STANDBY_NOT_CONFIGURED,
    PRODUCT_CONTROLLER_STATE_NETWORK_STANDBY,
    PRODUCT_CONTROLLER_STATE_LOW_POWER_STANDBY,
    PRODUCT_CONTROLLER_STATE_LOW_POWER_STANDBY_TRANSITION,
    PRODUCT_CONTROLLER_STATE_ON,
    PRODUCT_CONTROLLER_STATE_IDLE,
    PRODUCT_CONTROLLER_STATE_PLAYABLE,
    PRODUCT_CONTROLLER_STATE_PLAYING,
    PRODUCT_CONTROLLER_STATE_PLAYING_ACTIVE,
    PRODUCT_CONTROLLER_STATE_PLAYING_INACTIVE,
    PRODUCT_CONTROLLER_STATE_IDLE_VOICE_CONFIGURED,
    PRODUCT_CONTROLLER_STATE_IDLE_VOICE_NOT_CONFIGURED,
    PRODUCT_CONTROLLER_STATE_SOFTWARE_UPDATING,
    PRODUCT_CONTROLLER_STATE_FACTORY_DEFAULT,
    PRODUCT_CONTROLLER_STATE_PLAYING_DESELECTED,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED_SILENT,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED_NOT_SILENT,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED_SETUP,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED_NETWORK_SETUP,
    PRODUCT_CONTROLLER_STATE_PLAYING_SELECTED_SETUP_OTHER,
    PRODUCT_CONTROLLER_STATE_STOPPING_STREAMS,
    PRODUCT_CONTROLLER_STATE_PLAYABLE_TRANSITION,
    PRODUCT_CONTROLLER_STATE_PLAYABLE_TRANSITION_IDLE,
    PRODUCT_CONTROLLER_STATE_PLAYABLE_TRANSITION_NETWORK_STANDBY,
    PRODUCT_CONTROLLER_STATE_SOFTWARE_UPDATE_TRANSITION,
    PRODUCT_CONTROLLER_STATE_LOW_POWER_TRANSITION,
    PRODUCT_CONTROLLER_STATE_PLAYING_TRANSITION,
    PRODUCT_CONTROLLER_STATE_PLAYING_TRANSITION_SELECTED,

    //Start adding custom states here
    CUSTOM_PRODUCT_CONTROLLER_STATE_BOOTING = PRODUCT_CONTROLLER_STATE_BOOTING,
    CUSTOM_PRODUCT_CONTROLLER_STATE_SETUP = PRODUCT_CONTROLLER_STATE_SETUP,
    CUSTOM_PRODUCT_CONTROLLER_STATE_SOFTWARE_UPDATING,
    CUSTOM_PRODUCT_CONTROLLER_STATE_NETWORK_STANDBY = PRODUCT_CONTROLLER_STATE_NETWORK_STANDBY,
    CUSTOM_PRODUCT_CONTROLLER_STATE_ON = PRODUCT_CONTROLLER_STATE_ON
};
