/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense.h"
#include "CapSense_Control.h"
#include "CapSense_Filter.h"
#include "CapSense_Processing.h"
#include "CapSense_Sensing.h"
#include "CapSense_Structure.h"
#include "CapSense_Tuner.h"
#include "CapSense_Configuration.h"
#include "CapSense_SensingCSD_LL.h"
#include "CapSense_RegisterMap.h"
#include "CapSense_Centroid_LL.h"
#include "CapSense_SmartSense_LL.h"
#include "TACT.h"
#include "TACT_aliases.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "TimerISR.h"
#include "SPIM.h"
#include "SPIM_SPI_UART.h"
#include "SPIM_PINS.h"
#include "SPIM_SPI_UART_PVT.h"
#include "SPIM_PVT.h"
#include "SPIM_BOOT.h"
#include "Blank.h"
#include "Blank_aliases.h"
#include "Latch.h"
#include "Latch_aliases.h"
#include "CapSense_ISR.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_SCB_IRQ.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "SPIM_SCBCLK.h"
#include "SPIM_sclk_m.h"
#include "SPIM_sclk_m_aliases.h"
#include "SPIM_mosi_m.h"
#include "SPIM_mosi_m_aliases.h"
#include "SPIM_SCB_IRQ.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyLFClk.h"

/*[]*/

