#!/usr/bin/python2.7
#
# Invoked via pts-handler to display pages related to accessories diagnostics.
#
import os
import sys
import re
import json
import datetime
import subprocess

#if "get" or "put" argument specified, perform corresponding action on FrontDoor
if len(sys.argv) > 1:

    #if "get" argument, perform get request and output as text, using "Refresh" option to continously poll
    if sys.argv[1]== "get":

        output = subprocess.Popen(["frontdoorutil","/accessories"],stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()

        print """HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nCache-Control: no-cache\r\nRefresh: 1\r\n\r"""

        print datetime.datetime.now()

        try:
            data = json.loads(output[0])
            print "Enabled:"+json.dumps(data['body']['enabled'],indent=4);
            print "Pairing: "+json.dumps(data['body']['pairing'],indent=4);

        except ValueError:
            print output[1]+"\n"
            sys.exit()
        except KeyError:
            print output[0]+"\n"
            sys.exit()

    #if "put" argument, perform put request with utility. Result will be reflected in next "get"
    elif sys.argv[1]=="put":
        subprocess.Popen(["frontdoorutil","/accessories","{\"pairing\": true}"],stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
      
##Print out main page  
else:
    print """
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title>Accessories Diagnostics</title>
        <style type="text/css">
            body {
                font-family: Verdana, Arial, Helvetica, sans-serif;
                overflow: auto;
            }
            hr {
                border: 1px solid blue;
                color: #fff;
                background-color: #fff;
                height: 1px;
                width: 100%;
            }
            iframe {
                background-color: lightgrey;
                white-space: pre-wrap;
                border: thin dotted;
                position:relative;
                height: 10em;
                width: 98%;
                margin: 1%;
                padding 1em;
                display: block;
                overflow: scroll;
            }
        </style>
    </head>

    <body>
        <h1 id='header'>Accessories</h1>
        <hr>
        <li>FrontDoor Endpoint
        <iframe src="/diag/accessories/get"></iframe>   <!-- inline frame pulls from "get" portion of CGI script, while button fetches "pull" request -->
        <input id='submit-payload-button' type='submit' value='Pairing Start' class='submit btn waves-effect waves-light' onclick='fetch("/diag/accessories/put")'/>
        <hr>
    </body>
</html>
"""
