#!/usr/bin/python2.7
#
# Invoked via pts-handler to display pages related to AdaptIQ diagnostics.
#
import os
import sys
import re
import json
import datetime
import subprocess

# If "get" or "put" argument specified, perform corresponding action on FrontDoor
if len(sys.argv) > 1:

    # If "get" argument, perform get request and output as text, using "Refresh" option to continously poll.
    if sys.argv[1]== "get":

        output = subprocess.Popen(["frontdoorutil","/adaptiq"],stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()

        # HTTP Refresh header used to continuously poll data from the endpoint. Ensure users see up-to-date info.
        print """HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nCache-Control: no-cache\r\nRefresh: 1\r\n\r"""

        print datetime.datetime.now()

        try:
            data = json.loads(output[0])
            print "hpConnected: "+json.dumps(data['body']['hpConnected'],indent=4);
            print "smState: "+json.dumps(data['body']['smState'],indent=4);

        # Catch error Parsing JSON, output error messages from utility.
        except ValueError:
            print output[1]
            sys.exit()

        # Catch Error finding specific fields, output whatever message we did receive.
        except KeyError:
            print output[0]
            sys.exit()

    # If "put" argument, perform put request with utility. Result will be reflected in next "get".
    elif sys.argv[1]=="put":
        subprocess.Popen(["frontdoorutil","/adaptiq","{\"action\": \"ACTION_ENTER\"}"],stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
      
# Else, print out main page  
else:
    print """
<!DOCTYPE HTML>
<html>
    <script>
    function aiqstart() {
        var url = "/diag/adaptiq/put";
        var request = new XMLHttpRequest();
        request.open('PUT', url);
        request.send(null);
    }
    </script
    <head>
        <meta charset="utf-8">
        <title>AdaptIQ Diagnostics</title>
        <style type="text/css">
            body {
                font-family: Verdana, Arial, Helvetica, sans-serif;
                overflow: auto;
            }
            hr {
                border: 1px solid blue;
                color: #fff;
                background-color: #fff;
                height: 1px;
                width: 100%;
            }
            iframe {
                background-color: lightgrey;
                white-space: pre-wrap;
                border: thin dotted;
                position:relative;
                height: 10em;
                width: 98%;
                margin: 1%;
                padding 1em;
                display: block;
                overflow: scroll;
            }
        </style>
    </head>

    <body>
        <h1 id='header'>AdaptIQ</h1>
        <hr>
        <li>FrontDoor Endpoint
        <iframe src="/diag/adaptiq/get"></iframe>   <!-- inline frame pulls from "get" portion of CGI script, while button fetches "pull" request -->
        <input id='submit-payload-button' type='submit' value='AdaptIQ Start' class='submit btn waves-effect waves-light' onclick='aiqstart()'/>
        <hr>
    </body>
</html>
"""
