#!/usr/bin/python2.7
#
# Show an image on the display.
#
# For example, for the URL
#
#   http://203.0.113.1/diag/display/black.png?show
#
# this script invokes as
#
#   display black.png?show
#
# This shows the specified image on the display and outputs a simple HTTP
# response, "OK".
#
# Without the "?show" part, the script returns the image as the HTTP
# response.
#
import os
import sys
import subprocess

if len(sys.argv) != 2:
    raise Exception("wrong usage " + str(sys.argv))
image = sys.argv[1]

params = None
i = image.find("?")
if i != -1:
    params = image[i+1:]
    image = image[:i]

# Protect against potentially malicious pathnames.
if "/" in image or not image.endswith(".png") or not os.path.exists(image) or \
   os.path.islink(image):
    raise Exception("bad image name: " + image)

if params == "show":
    # Used by Test/mfgdata/diagnostics_mfgdata_page.py
    subprocess.call(["logger", "display-test", image])

    devnull = open("/dev/null", "w")

    try:
        os.remove("/var/run/shepherd/Shepherd-Monaco.xml")
        removed = True
    except:
        removed = False
    if removed:
        # Stop Monaco from managing the display.
        subprocess.call(["shepherd-wait", "/var/run/shepherd", "/var/run/shepherd/pid"],
                        stdout=devnull, stderr=subprocess.STDOUT)
        # Special handling for dyz-shm started by run_wpe.sh (yuck).
        # Delete this when we switch to Dinghy.
        subprocess.call(["killwait", "dyz-shm"],
                        stdout=devnull, stderr=subprocess.STDOUT)

    # Show the image on the unit's display and
    # send "OK" as the HTTP response.
    subprocess.call(["show_splash", image],
                    stdout=devnull, stderr=subprocess.STDOUT)

    print """\
HTTP/1.1 200 OK\r
Content-Type: text/plain\r
Cache-Control: no-cache\r
\r
OK\r"""

else:
    # Output the image as the HTTP response.
    print """\
HTTP/1.1 200 OK\r
Content-Type: image/png\r
\r"""
    sys.stdout.write(open(image, "rb").read())
