# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\work\Eddie\capsense\i2csimple\Bootloader.cydsn\Bootloader.cyprj
# Date: Thu, 18 May 2017 17:45:37 GMT
#set_units -time ns
create_clock -name {I2CS_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {I2CS_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]


# Component constraints for C:\work\Eddie\capsense\i2csimple\Bootloader.cydsn\TopDesign\TopDesign.cysch
# Project: C:\work\Eddie\capsense\i2csimple\Bootloader.cydsn\Bootloader.cyprj
# Date: Thu, 18 May 2017 17:45:37 GMT
