// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RepeatManagerKeyAction.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* KEY_EVENT_ACTION_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_RepeatManagerKeyAction_2eproto() {
  protobuf_AddDesc_RepeatManagerKeyAction_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RepeatManagerKeyAction.proto");
  GOOGLE_CHECK(file != NULL);
  KEY_EVENT_ACTION_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RepeatManagerKeyAction_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_RepeatManagerKeyAction_2eproto() {
}

void protobuf_AddDesc_RepeatManagerKeyAction_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034RepeatManagerKeyAction.proto*\260\014\n\020KEY_E"
    "VENT_ACTION\022(\n\033INVALID_BUTTON_EVENT_ACTI"
    "ON\020\377\377\377\377\377\377\377\377\377\001\022\025\n\021BUTTON_EVENT_PLAY\020\000\022\026\n\022"
    "BUTTON_EVENT_PAUSE\020\001\022\025\n\021BUTTON_EVENT_STO"
    "P\020\002\022\037\n\033BUTTON_EVENT_PREVIOUS_TRACK\020\003\022\033\n\027"
    "BUTTON_EVENT_NEXT_TRACK\020\004\022\032\n\026BUTTON_EVEN"
    "T_THUMBS_UP\020\005\022\034\n\030BUTTON_EVENT_THUMBS_DOW"
    "N\020\006\022\026\n\022BUTTON_EVENT_POWER\020\007\022\031\n\025BUTTON_EV"
    "ENT_BOOKMARK\020\010\022\025\n\021BUTTON_EVENT_MUTE\020\t\022\032\n"
    "\026BUTTON_EVENT_VOLUME_UP\020\n\022\034\n\030BUTTON_EVEN"
    "T_VOLUME_DOWN\020\013\022\031\n\025BUTTON_EVENT_PRESET_1"
    "\020\014\022\031\n\025BUTTON_EVENT_PRESET_2\020\r\022\031\n\025BUTTON_"
    "EVENT_PRESET_3\020\016\022\031\n\025BUTTON_EVENT_PRESET_"
    "4\020\017\022\031\n\025BUTTON_EVENT_PRESET_5\020\020\022\031\n\025BUTTON"
    "_EVENT_PRESET_6\020\021\022\032\n\026BUTTON_EVENT_AUX_IN"
    "PUT\020\022\022\033\n\027BUTTON_EVENT_SHUFFEL_ON\020\023\022\034\n\030BU"
    "TTON_EVENT_SHUFFEL_OFF\020\024\022\033\n\027BUTTON_EVENT"
    "_REPEAT_OFF\020\025\022\033\n\027BUTTON_EVENT_REPEAT_ONE"
    "\020\026\022\033\n\027BUTTON_EVENT_REPEAT_ALL\020\027\022\033\n\027BUTTO"
    "N_EVENT_PLAY_PAUSE\020\030\022\035\n\031BUTTON_EVENT_ADD"
    "_FAVORITE\020\031\022 \n\034BUTTON_EVENT_REMOVE_FAVOR"
    "ITE\020\032\022\032\n\026BUTTON_EVENT_BLUETOOTH\020\033\022%\n!BUT"
    "TON_EVENT_VOLUME_DOWN_PRESET_1\020\034\022%\n!BUTT"
    "ON_EVENT_VOLUME_DOWN_PRESET_2\020\035\022%\n!BUTTO"
    "N_EVENT_PRESET_1_VOLUME_DOWN\020\036\022%\n!BUTTON"
    "_EVENT_PRESET_2_VOLUME_DOWN\020\037\022%\n!BUTTON_"
    "EVENT_PRESET_3_VOLUME_DOWN\020 \022%\n!BUTTON_E"
    "VENT_PRESET_4_VOLUME_DOWN\020!\022%\n!BUTTON_EV"
    "ENT_PRESET_5_VOLUME_DOWN\020\"\022%\n!BUTTON_EVE"
    "NT_PRESET_6_VOLUME_DOWN\020#\022#\n\037BUTTON_EVEN"
    "T_PRESET_1_VOLUME_UP\020$\022#\n\037BUTTON_EVENT_P"
    "RESET_2_VOLUME_UP\020%\022#\n\037BUTTON_EVENT_PRES"
    "ET_3_VOLUME_UP\020&\022#\n\037BUTTON_EVENT_PRESET_"
    "4_VOLUME_UP\020\'\022#\n\037BUTTON_EVENT_PRESET_5_V"
    "OLUME_UP\020(\022#\n\037BUTTON_EVENT_PRESET_6_VOLU"
    "ME_UP\020)\022\037\n\033BUTTON_EVENT_PRESET_1_2_3_4\020*"
    "\022\036\n\032BUTTON_EVENT_LONG_PRESET_5\020+\022#\n\037BUTT"
    "ON_EVENT_EXTRA_LONG_PRESET5\020,\022 \n\034BUTTON_"
    "EVENT_PLAY_PRESET_1_2\020-\022%\n!BUTTON_EVENT_"
    "LONG_PLAY_PRESET_1_2\020.\022!\n\035BUTTON_EVENT_L"
    "ONGEST_PRESET_5\020/", 1617);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RepeatManagerKeyAction.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RepeatManagerKeyAction_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RepeatManagerKeyAction_2eproto {
  StaticDescriptorInitializer_RepeatManagerKeyAction_2eproto() {
    protobuf_AddDesc_RepeatManagerKeyAction_2eproto();
  }
} static_descriptor_initializer_RepeatManagerKeyAction_2eproto_;

const ::google::protobuf::EnumDescriptor* KEY_EVENT_ACTION_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return KEY_EVENT_ACTION_descriptor_;
}
bool KEY_EVENT_ACTION_IsValid(int value) {
  switch(value) {
    case -1:
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
