// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RepeatManager.proto

#ifndef PROTOBUF_RepeatManager_2eproto__INCLUDED
#define PROTOBUF_RepeatManager_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace RepeatManager {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RepeatManager_2eproto();
void protobuf_AssignDesc_RepeatManager_2eproto();
void protobuf_ShutdownFile_RepeatManager_2eproto();

class Repeat;

// ===================================================================

class Repeat : public ::google::protobuf::Message {
 public:
  Repeat();
  virtual ~Repeat();
  
  Repeat(const Repeat& from);
  
  inline Repeat& operator=(const Repeat& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Repeat& default_instance();
  
  void Swap(Repeat* other);
  
  // implements Message ----------------------------------------------
  
  Repeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Repeat& from);
  void MergeFrom(const Repeat& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 keyNumber = 1;
  inline bool has_keynumber() const;
  inline void clear_keynumber();
  static const int kKeyNumberFieldNumber = 1;
  inline ::google::protobuf::uint32 keynumber() const;
  inline void set_keynumber(::google::protobuf::uint32 value);
  
  // optional uint32 keyState = 2;
  inline bool has_keystate() const;
  inline void clear_keystate();
  static const int kKeyStateFieldNumber = 2;
  inline ::google::protobuf::uint32 keystate() const;
  inline void set_keystate(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:RepeatManager.Repeat)
 private:
  inline void set_has_keynumber();
  inline void clear_has_keynumber();
  inline void set_has_keystate();
  inline void clear_has_keystate();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 keynumber_;
  ::google::protobuf::uint32 keystate_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_RepeatManager_2eproto();
  friend void protobuf_AssignDesc_RepeatManager_2eproto();
  friend void protobuf_ShutdownFile_RepeatManager_2eproto();
  
  void InitAsDefaultInstance();
  static Repeat* default_instance_;
};
// ===================================================================


// ===================================================================

// Repeat

// optional uint32 keyNumber = 1;
inline bool Repeat::has_keynumber() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Repeat::set_has_keynumber() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Repeat::clear_has_keynumber() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Repeat::clear_keynumber() {
  keynumber_ = 0u;
  clear_has_keynumber();
}
inline ::google::protobuf::uint32 Repeat::keynumber() const {
  return keynumber_;
}
inline void Repeat::set_keynumber(::google::protobuf::uint32 value) {
  set_has_keynumber();
  keynumber_ = value;
}

// optional uint32 keyState = 2;
inline bool Repeat::has_keystate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Repeat::set_has_keystate() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Repeat::clear_has_keystate() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Repeat::clear_keystate() {
  keystate_ = 0u;
  clear_has_keystate();
}
inline ::google::protobuf::uint32 Repeat::keystate() const {
  return keystate_;
}
inline void Repeat::set_keystate(::google::protobuf::uint32 value) {
  set_has_keystate();
  keystate_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RepeatManager

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RepeatManager_2eproto__INCLUDED
