// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RepeatManager.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace RepeatManager {

namespace {

const ::google::protobuf::Descriptor* Repeat_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Repeat_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_RepeatManager_2eproto() {
  protobuf_AddDesc_RepeatManager_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "RepeatManager.proto");
  GOOGLE_CHECK(file != NULL);
  Repeat_descriptor_ = file->message_type(0);
  static const int Repeat_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Repeat, keynumber_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Repeat, keystate_),
  };
  Repeat_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Repeat_descriptor_,
      Repeat::default_instance_,
      Repeat_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Repeat, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Repeat, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Repeat));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_RepeatManager_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Repeat_descriptor_, &Repeat::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_RepeatManager_2eproto() {
  delete Repeat::default_instance_;
  delete Repeat_reflection_;
}

void protobuf_AddDesc_RepeatManager_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023RepeatManager.proto\022\rRepeatManager\"-\n\006"
    "Repeat\022\021\n\tkeyNumber\030\001 \001(\r\022\020\n\010keyState\030\002 "
    "\001(\r", 83);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RepeatManager.proto", &protobuf_RegisterTypes);
  Repeat::default_instance_ = new Repeat();
  Repeat::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_RepeatManager_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_RepeatManager_2eproto {
  StaticDescriptorInitializer_RepeatManager_2eproto() {
    protobuf_AddDesc_RepeatManager_2eproto();
  }
} static_descriptor_initializer_RepeatManager_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Repeat::kKeyNumberFieldNumber;
const int Repeat::kKeyStateFieldNumber;
#endif  // !_MSC_VER

Repeat::Repeat()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Repeat::InitAsDefaultInstance() {
}

Repeat::Repeat(const Repeat& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Repeat::SharedCtor() {
  _cached_size_ = 0;
  keynumber_ = 0u;
  keystate_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Repeat::~Repeat() {
  SharedDtor();
}

void Repeat::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Repeat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Repeat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Repeat_descriptor_;
}

const Repeat& Repeat::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_RepeatManager_2eproto();  return *default_instance_;
}

Repeat* Repeat::default_instance_ = NULL;

Repeat* Repeat::New() const {
  return new Repeat;
}

void Repeat::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    keynumber_ = 0u;
    keystate_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Repeat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 keyNumber = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &keynumber_)));
          set_has_keynumber();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_keyState;
        break;
      }
      
      // optional uint32 keyState = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_keyState:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &keystate_)));
          set_has_keystate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Repeat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 keyNumber = 1;
  if (has_keynumber()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->keynumber(), output);
  }
  
  // optional uint32 keyState = 2;
  if (has_keystate()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->keystate(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Repeat::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional uint32 keyNumber = 1;
  if (has_keynumber()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->keynumber(), target);
  }
  
  // optional uint32 keyState = 2;
  if (has_keystate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->keystate(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Repeat::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 keyNumber = 1;
    if (has_keynumber()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->keynumber());
    }
    
    // optional uint32 keyState = 2;
    if (has_keystate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->keystate());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Repeat::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Repeat* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Repeat*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Repeat::MergeFrom(const Repeat& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_keynumber()) {
      set_keynumber(from.keynumber());
    }
    if (from.has_keystate()) {
      set_keystate(from.keystate());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Repeat::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Repeat::CopyFrom(const Repeat& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Repeat::IsInitialized() const {
  
  return true;
}

void Repeat::Swap(Repeat* other) {
  if (other != this) {
    std::swap(keynumber_, other->keynumber_);
    std::swap(keystate_, other->keystate_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Repeat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Repeat_descriptor_;
  metadata.reflection = Repeat_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace RepeatManager

// @@protoc_insertion_point(global_scope)
