// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RepeatManagerKeyAction.proto

#ifndef PROTOBUF_RepeatManagerKeyAction_2eproto__INCLUDED
#define PROTOBUF_RepeatManagerKeyAction_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RepeatManagerKeyAction_2eproto();
void protobuf_AssignDesc_RepeatManagerKeyAction_2eproto();
void protobuf_ShutdownFile_RepeatManagerKeyAction_2eproto();


enum KEY_EVENT_ACTION {
  INVALID_BUTTON_EVENT_ACTION = -1,
  BUTTON_EVENT_PLAY = 0,
  BUTTON_EVENT_PAUSE = 1,
  BUTTON_EVENT_STOP = 2,
  BUTTON_EVENT_PREVIOUS_TRACK = 3,
  BUTTON_EVENT_NEXT_TRACK = 4,
  BUTTON_EVENT_THUMBS_UP = 5,
  BUTTON_EVENT_THUMBS_DOWN = 6,
  BUTTON_EVENT_POWER = 7,
  BUTTON_EVENT_BOOKMARK = 8,
  BUTTON_EVENT_MUTE = 9,
  BUTTON_EVENT_VOLUME_UP = 10,
  BUTTON_EVENT_VOLUME_DOWN = 11,
  BUTTON_EVENT_PRESET_1 = 12,
  BUTTON_EVENT_PRESET_2 = 13,
  BUTTON_EVENT_PRESET_3 = 14,
  BUTTON_EVENT_PRESET_4 = 15,
  BUTTON_EVENT_PRESET_5 = 16,
  BUTTON_EVENT_PRESET_6 = 17,
  BUTTON_EVENT_AUX_INPUT = 18,
  BUTTON_EVENT_SHUFFEL_ON = 19,
  BUTTON_EVENT_SHUFFEL_OFF = 20,
  BUTTON_EVENT_REPEAT_OFF = 21,
  BUTTON_EVENT_REPEAT_ONE = 22,
  BUTTON_EVENT_REPEAT_ALL = 23,
  BUTTON_EVENT_PLAY_PAUSE = 24,
  BUTTON_EVENT_ADD_FAVORITE = 25,
  BUTTON_EVENT_REMOVE_FAVORITE = 26,
  BUTTON_EVENT_BLUETOOTH = 27,
  BUTTON_EVENT_VOLUME_DOWN_PRESET_1 = 28,
  BUTTON_EVENT_VOLUME_DOWN_PRESET_2 = 29,
  BUTTON_EVENT_PRESET_1_VOLUME_DOWN = 30,
  BUTTON_EVENT_PRESET_2_VOLUME_DOWN = 31,
  BUTTON_EVENT_PRESET_3_VOLUME_DOWN = 32,
  BUTTON_EVENT_PRESET_4_VOLUME_DOWN = 33,
  BUTTON_EVENT_PRESET_5_VOLUME_DOWN = 34,
  BUTTON_EVENT_PRESET_6_VOLUME_DOWN = 35,
  BUTTON_EVENT_PRESET_1_VOLUME_UP = 36,
  BUTTON_EVENT_PRESET_2_VOLUME_UP = 37,
  BUTTON_EVENT_PRESET_3_VOLUME_UP = 38,
  BUTTON_EVENT_PRESET_4_VOLUME_UP = 39,
  BUTTON_EVENT_PRESET_5_VOLUME_UP = 40,
  BUTTON_EVENT_PRESET_6_VOLUME_UP = 41,
  BUTTON_EVENT_PRESET_1_2_3_4 = 42,
  BUTTON_EVENT_LONG_PRESET_5 = 43,
  BUTTON_EVENT_EXTRA_LONG_PRESET5 = 44,
  BUTTON_EVENT_PLAY_PRESET_1_2 = 45,
  BUTTON_EVENT_LONG_PLAY_PRESET_1_2 = 46,
  BUTTON_EVENT_LONGEST_PRESET_5 = 47
};
bool KEY_EVENT_ACTION_IsValid(int value);
const KEY_EVENT_ACTION KEY_EVENT_ACTION_MIN = INVALID_BUTTON_EVENT_ACTION;
const KEY_EVENT_ACTION KEY_EVENT_ACTION_MAX = BUTTON_EVENT_LONGEST_PRESET_5;
const int KEY_EVENT_ACTION_ARRAYSIZE = KEY_EVENT_ACTION_MAX + 1;

const ::google::protobuf::EnumDescriptor* KEY_EVENT_ACTION_descriptor();
inline const ::std::string& KEY_EVENT_ACTION_Name(KEY_EVENT_ACTION value) {
  return ::google::protobuf::internal::NameOfEnum(
    KEY_EVENT_ACTION_descriptor(), value);
}
inline bool KEY_EVENT_ACTION_Parse(
    const ::std::string& name, KEY_EVENT_ACTION* value) {
  return ::google::protobuf::internal::ParseNamedEnum<KEY_EVENT_ACTION>(
    KEY_EVENT_ACTION_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< KEY_EVENT_ACTION>() {
  return KEY_EVENT_ACTION_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RepeatManagerKeyAction_2eproto__INCLUDED
