#!/bin/sh
echo "wpe postinst"
set -e
CR='
'
test -d '/opt/Bose/wpe'/share/dbus || exit 0

ok=true
for pkgpath in $(IFS=${CR} find '/opt/Bose/wpe'/share/dbus/ -name '*.conf')
do
	etcpath="/etc/dbus-1/system.d/$(basename "${pkgpath}")"
	if test -r "${etcpath}" ; then
		echo "wpe: ${etcpath}: Already exists."
		ok=false
	else
		echo "wpe: ${etcpath} -> ${pkgpath}"
		ln -s "${pkgpath}" "${etcpath}"
	fi
done

if ! ${ok} ; then
	echo "wpe: Setup may not be complete."
    # Set Progress End - Error
    /opt/Bose/bin/ProgressReport -n $PackageName -e 1 -i 0 -r APQ -b 0 -p 100
	exit 1
fi
# Set Progress End - Success
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r APQ -b 0 -p 100
exit 0
