#!/bin/bash
#
# Add build outputs to the deploy directory for ElectricCommander.
# See EC/deploy.txt.
#

if (( $# != 2 )); then
    echo >&2 "usage: $0 builds-dir deploy-dir"
    exit 1
fi
builds_dir=$1; shift
deploy_dir=$1; shift
downgrade_zip_dir="$deploy_dir/forDowngrade"

rm -rf "$deploy_dir"
mkdir -p "$deploy_dir" || exit
mkdir -p "$downgrade_zip_dir" || exit

files=(
    "$builds_dir/product-unstripped.tar.gz"
    "$builds_dir/product-ipk-stage/component-info.gz"
    "$builds_dir/components.svgz"
    "$builds_dir/components.txt"
    "$builds_dir/package/product.tar"
    "$builds_dir/product_update.zip"
    "$builds_dir/product_update_no_hsp.zip"
    "$builds_dir"/eddie_package_*.bos
    "$builds_dir"/lpm_eddie_combined_*.hex
    "$builds_dir/lpm_package.xml"
    "$builds_dir/lpm_blob_configuration.xml"
)

cp "${files[@]}" "$deploy_dir" || exit
cp "$builds_dir/product_update_for_downgrade.zip" "$downgrade_zip_dir" || exit
