#!/bin/bash
#
# Add build outputs to the deploy directory for ElectricFlow.
# See EC/deploy.txt.
#

if (( $# != 3 )); then
    echo >&2 "usage: $0 builds-dir deploy-dir disableGVA(true/false)"
    exit 1
fi
builds_dir=$1; shift
deploy_dir=$1; shift
disableGVA=$1; shift

src_dir=$(cd "$(dirname "$0")/.." && echo "$PWD") || exit

rm -rf "$deploy_dir"
mkdir -p "$deploy_dir" || exit

files=(
    "$src_dir/components.json"
    "$builds_dir/auth_util.py"
    "$builds_dir/product-unstripped.tar.gz"
    "$builds_dir/product-ipk-stage/component-info.gz"
    "$builds_dir"/components*
    "$builds_dir/package/product.tar"
    "$builds_dir/product_update.zip"
    "$builds_dir/product_update_no_hsp.zip"
    "$builds_dir"/eddie_package_*.bos
    "$builds_dir"/lpm_eddie_combined_*.hex
    "$builds_dir/lpm_package.xml"
    "$builds_dir/lpm_blob_configuration.xml"
)

cp "${files[@]}" "$deploy_dir" || exit

if [ $disableGVA = true ]; then
    cp "$builds_dir/product_update_nogva.zip" "$deploy_dir" || exit
fi
