#!/bin/bash
#
# Create an IPK file for installing DinghyWebBrowser (WPE) with opkg.
#
# To install:
#   opkg install -d bose wpe.ipk
#
# The file /etc/opkg/opkg.conf should contain this line:
#   dest bose /opt/Bose
#
# To uninstall:
#   opkg remove wpe
#
this=${0##*/} # this script's name

cfg=Release

tryhelp () {
    echo >&2 "Try '$this --help' for more information."
    exit 1
}
opts=$(getopt --name "$this" --shell sh \
    -o uh \
    -l "help" \
    -- "$@") || tryhelp
eval set -- "$opts"
while :; do
    arg="$1"; shift
    case "$arg" in
    (--help | -h)
        cat <<EOF
Usage: $this [options]

Create an IPK file for installing WPE with opkg.

Options:
EOF
        exit 0
        ;;

    (--) break ;;
    (*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
    esac
done

if (( $# != 0 )); then
    echo >&2 "$this: unexpected argument '$1'"
    tryhelp
fi

function put_script {
    local file="$1"; shift
    cat "$@" >"$file" || exit
    chmod 755 "$file" || exit
}

here=$(cd "$(dirname $0)" && echo "$PWD") || exit
wspace=$(cd "$here/.." && echo "$PWD") || exit

wpe_dir=$(components get DinghyWebBrowser-qc8017_64 installed_location) || exit
wpe_ver=$(components get DinghyWebBrowser-qc8017_64 selected_version) || exit
wpe_ver=${wpe_ver##*/}

stage=$wspace/builds/$cfg/wpe-ipk-stage
rm -rf "$stage"
echo "Stage directory $stage"

output_dir=$wspace/builds/$cfg
opt_dir=$stage/Bose
mkdir -p "$output_dir" "$opt_dir" || exit

echo "Package version \"$wpe_ver\""
cp -f "$wpe_dir/wpe.ipk" "$opt_dir/" || exit
cd "$opt_dir" && ar -x "$opt_dir/wpe.ipk" || exit
tar -xzf "$opt_dir/control.tar.gz" || exit

PackageName=wpe

cat >"$stage/control" <<EOF || exit
Package: $PackageName
Version: $wpe_ver
Description: WPE WebKit bundle $wpe_ver
Section: web browser app
Priority: required
License: Commercial
Architecture: armv7a-vfp-neon
OE: web browser app
Homepage: http://www.bose.com/
Source: None
EOF

# Installer scripts
cp -f "$wspace/scripts/wpe-ipk/postinst" "$stage/"
cp -f "$wspace/scripts/wpe-ipk/prerm" "$stage/"

put_script "$stage/postrm" <<EOF
#!/bin/sh
echo "wpe postrm"
exit 0
EOF

put_script "$stage/preinst" <<EOF
#!/bin/sh
echo "wpe preinst"
# Set Progress Start
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r APQ -b 0 -p 1
exit 0
EOF

# -----------------------------------------------------------------------------
# Stage area is complete.  Package it into a *.ipk file.

cd "$stage" || exit
tar --owner=0 --group=0 -czf control.tar.gz control pre* post* || exit
mv "$opt_dir/data.tar.gz" "$stage"/ || exit
echo "2.0" > debian-binary || exit

ipk_dir=$wspace/builds/$cfg
ipk=$ipk_dir/wpe.ipk
mkdir -p "$ipk_dir" || exit
rm -f "$ipk"
ar -crf "$ipk" control.tar.gz data.tar.gz debian-binary || exit
echo "Created $ipk"
