#!/bin/bash
#
# Create an IPK file for installing Toledo with opkg.
#
# To install:
#   opkg install -d bose toledo.ipk
#
# The file /etc/opkg/opkg.conf should contain this line:
#   dest bose /opt/Bose
#
# To uninstall:
#   opkg remove toledo
#
this=${0##*/} # this script's name

cfg=Release

tryhelp () {
    echo >&2 "Try '$this --help' for more information."
    exit 1
}
opts=$(getopt --name "$this" --shell sh \
    -o uh \
    -l "help" \
    -- "$@") || tryhelp
eval set -- "$opts"
while :; do
    arg="$1"; shift
    case "$arg" in
    (--help | -h)
        cat <<EOF
Usage: $this [options]

Create an IPK file for installing Toledo with opkg.

Options:
EOF
        exit 0
        ;;

    (--) break ;;
    (*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
    esac
done

if (( $# != 0 )); then
    echo >&2 "$this: unexpected argument '$1'"
    tryhelp
fi

function put_script {
    local file="$1"; shift
    cat "$@" >"$file" || exit
    chmod 755 "$file" || exit
}

here=$(cd "$(dirname $0)" && echo "$PWD") || exit
wspace=$(cd "$here/.." && echo "$PWD") || exit

toledo_dir=$(components get BoseWebToledo installed_location) || exit
toledo_ver=$(components get BoseWebToledo selected_version) || exit
toledo_ver=${toledo_ver##*/}

stage=$wspace/builds/$cfg/toledo-ipk-stage
rm -rf "$stage"
echo "Stage directory $stage"

output_dir=$wspace/builds/$cfg
opt_dir=$stage/Bose
mkdir -p "$output_dir" "$opt_dir" || exit
mkdir -p "$output_dir" "$opt_dir/bin" || exit

echo "Package version \"$toledo_ver\""
"$wspace"/scripts/validate-version "$toledo_ver" || exit
cp -rf "$toledo_dir"/toledo "$opt_dir/" || exit

cp -f  "$toledo_dir"/run_toledo "$opt_dir/bin" || exit
PackageName=toledo

cat >"$stage/control" <<EOF || exit
Package: $PackageName
Version: $toledo_ver
Description: Bose Web Toledo Package version $toledo_ver
 Bose Web Toledo
Section: web browser app
Priority: required
License: Commercial
Architecture: armv7a-vfp-neon
OE: web browser app
Homepage: http://www.bose.com/
#Depends: libc6 (>= 2.21)
Source: None
EOF

# Installer scripts
put_script "$stage/postinst" <<EOF
#!/bin/sh
echo "toledo postinst"
# Set Progress End
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r LPM -b 0 -p 100
exit 0
EOF

put_script "$stage/postrm" <<EOF
#!/bin/sh
echo "toledo postrm"
exit 0
EOF

put_script "$stage/preinst" <<EOF
#!/bin/sh
echo "toledo preinst"
# Set Progress Start
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 0 -r LPM -b 0 -p 1
exit 0
EOF

put_script "$stage/prerm" <<EOF
#!/bin/sh
echo "toledo prerm"
exit 0
EOF

# -----------------------------------------------------------------------------
# Stage area is complete.  Package it into a *.ipk file.

cd "$stage" || exit
tar --owner=0 --group=0 -czf control.tar.gz control pre* post* || exit
tar --owner=0 --group=0 -czf data.tar.gz -C "$opt_dir" . || exit
echo "2.0" > debian-binary || exit

ipk_dir=$wspace/builds/$cfg
ipk=$ipk_dir/toledo.ipk
mkdir -p "$ipk_dir" || exit
rm -f "$ipk"
ar -crf "$ipk" control.tar.gz data.tar.gz debian-binary || exit
echo "Created $ipk"
