#!/bin/bash
#
# Create an IPK file for installing Riviera HSP with opkg.
#
# To install:
#   opkg install -d bose hsp.ipk
#
# The file /etc/opkg/opkg.conf should contain this line:
#   dest bose /opt/Bose
#
# To uninstall:
#   opkg remove hsp
#
# CAUTION: HSP IPK, if interrupted / have issues, 
#          can corrupt the device. 
#          Please have it QFILed if this happen
#
this=${0##*/} # this script's name

tryhelp () {
    echo >&2 "Try '$this --help' for more information."
    exit 1
}
opts=$(getopt --name "$this" --shell sh \
    -o uh \
    -l "help" \
    -- "$@") || tryhelp
eval set -- "$opts"
while :; do
    arg="$1"; shift
    case "$arg" in
    (--help | -h)
        cat <<EOF
Usage: $this [options] <Release|Debug>

Create an IPK file for installing Riviera HSP with opkg.

Options:
EOF
        exit 0
        ;;

    (--) break ;;
    (*)  echo >&2 "$this: internal error at '$arg'"; exit 1 ;;
    esac
done

if (( $# != 1 )); then
    echo >&2 "$this: wrong usage"
    tryhelp
fi
cfg=$1; shift

function put_script {
    local file="$1"; shift
    cat "$@" >"$file" || exit
    chmod 755 "$file" || exit
}

here=$(cd "$(dirname $0)" && echo "$PWD") || exit
wspace=$(cd "$here/.." && echo "$PWD") || exit

riviera_hsp_images_dir=$(components get Riviera-HSP-Images installed_location) || exit
riviera_hsp_ver=$(components get Riviera-HSP-Images selected_version) || exit
riviera_hsp_ver=${riviera_hsp_ver##*/}

arch=arm-oemllib32-linux
sysroot=$riviera_toolchain_dir/sdk/sysroots/$(uname -m)-oesdk-linux
tool_prefix=$sysroot/usr/bin/$arch/$arch-

stage=$wspace/builds/$cfg/hsp-ipk-stage
rm -rf "$stage"
echo "Stage directory $stage"

opt_dir=$stage/Bose
mkdir -p "$opt_dir/hsp" || exit

echo "$riviera_hsp_ver" > "$opt_dir"/hsp/HSP_VERSION || exit
echo "Package version \"$riviera_hsp_ver\""
cp "$riviera_hsp_images_dir"/update_ext4.zip "$opt_dir/hsp/" || exit
PackageName=hsp

cat >"$stage/control" <<EOF || exit
Package: $PackageName
Version: $riviera_hsp_ver
Description: Hardware Support Package version $riviera_hsp_ver
 The Riviera HSP
Section: soundtouch
Priority: required
License: Commercial
Architecture: armv7a-vfp-neon
OE: soundtouch
Homepage: http://www.bose.com/
#Depends: libc6 (>= 2.21)
Source: None
EOF

# Installer scripts
put_script "$stage/postinst" <<EOF
#!/bin/sh
echo "hsp postinst"
exiterror()
{
    # Set Progress End
    /opt/Bose/bin/ProgressReport -n $PackageName -e 1 -i 1 -r APQ -b 0 -p 100
    exit 1
}

if [ ! -f /opt/Bose/hsp/update_ext4.zip ]; then
    echo "/opt/Bose/hsp/update_ext4.zip not found"
    exiterror
fi

if [ -e /etc/initscripts/recovery-updater.sh ]
then
    /etc/initscripts/recovery-updater.sh /opt/Bose/hsp/update_ext4.zip || exiterror
fi

if ! grep -q /cache /proc/mounts; then
    echo "Mounting Cache"
    mount /dev/mmcblk0p26 /cache || exiterror
fi
mkdir -p /cache/recovery/ || exiterror
echo "--update_package=/opt/Bose/hsp/update_ext4.zip" > /cache/recovery/command || exiterror
echo "--idle_after" >> /cache/recovery/command || exiterror
# Set Progress End
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 1 -r RECOVERY -b 0 -p 100
exit 0
EOF

put_script "$stage/postrm" <<EOF
#!/bin/sh
echo "hsp postrm"
EOF

put_script "$stage/preinst" <<EOF
#!/bin/sh
echo "hsp preinst"
# This is temporary for IP2. 
# Should be removed in IP3, when stopping services is 
# taken care of by Shepherd / Product / SoftwareUpdateService. 
# Set Progress Start
/opt/Bose/bin/ProgressReport -n $PackageName -e 0 -i 1 -r RECOVERY -b 0 -p 1

echo "Stopping LPM"
pkill LPMService
exit 0

EOF

put_script "$stage/prerm" <<EOF
#!/bin/sh
echo "hsp prerm"
EOF

# -----------------------------------------------------------------------------
# Stage area is complete.  Package it into a *.ipk file.

cd "$stage" || exit
tar --owner=0 --group=0 -czf control.tar.gz control pre* post* || exit
tar --owner=0 --group=0 -czf data.tar.gz -C "$opt_dir" . || exit
echo "2.0" > debian-binary || exit

ipk_dir=$wspace/builds/$cfg
ipk=$ipk_dir/hsp.ipk
mkdir -p "$ipk_dir" || exit
rm -f "$ipk"
ar -crf "$ipk" control.tar.gz data.tar.gz debian-binary || exit
echo "Created $ipk"
