#!/usr/bin/python
import sys
import json
import re
from collections import OrderedDict

"""
Generate a default key file from the key list generated by 
the LPM's "ki" tap command
"""

def main():
  ki_file = open(sys.argv[1], "r")
  keymap = {'keyTable' : []}
  for line in ki_file:
#    print('{}'.format(line)) 
    pat = re.compile(r'\s+(0x..):\s+([^,]+),\s+([^\s]+)')
    match = pat.match(line)
    if match:
      val = int(match.group(1), 16)
      name = match.group(2)
      group = match.group(3)
      keymap['keyTable'].append(OrderedDict([
        ('Keys', [val]),
        ('TimeOut', 300),  
        ('Repeat', False), 
        ('ActionOnTimeout', False), 
        ('Event', val),
        ('Description', name),
      ]))

#TODO : clean up "Keys" output (collapse to a single line)
  s = json.dumps(keymap, indent=4)
  print('{}'.format(s))
  

if __name__ == '__main__':
  main()

