#!/usr/bin/python2.7
# ################# NOTICE ###################
# This script is deprecated and will not work as expected.
#
# Alternatively you may use scripts/upstage.
# Copy files from your workspace product staging area to the target system.
#
#   make product-ipk && scripts/upstage
#
# or just:
#
#   scripts/upstage -b
#
# ############################################

import sys

print("ERROR: Deprecated, see /scripts/upstage")
sys.exit(1)
