#!/bin/bash
#
# Reflash the LPM with the latest build.
#
this=${0##*/}

if (( $# > 0 )); then
    echo >&2 "$this: wrong usage"
    exit 1
fi

build=/home/softlib/verisoft/Eddie/Continuous/master

version=$(cat "$build/latest.txt") || exit
echo "Build $version"

ipk=$build/$version/eddie_lpm_updater_$version.ipk
ls -s "$ipk" || exit

echo Remount...
adb shell mount -oremount,rw /opt/Bose || exit

echo Uninstall...
adb shell opkg remove --force-remove eddie_lpm_updater  # ok if this fails

echo Copy...
adb push "$ipk" /tmp/new.ipk || exit

echo Install...
adb shell opkg -d bose install /tmp/new.ipk || exit

echo Remount...
adb shell mount -oremount,ro /opt/Bose || exit

echo Done
