#!/bin/bash
#
# Install Monaco IPK from the latest EC Continuous build or 
# from the .ipk file provided as an argument.
#
this=${0##*/}

if (( $# > 1 )); then
    echo >&2 "usage: $this [monaco.ipk]"
    exit 1
fi

if (( $# == 1 )) && [[ "$1" = *.ipk ]]; then
    ipk=$1
else
    cd "$(dirname "$0")/.." || exit
    ipk=$PWD/builds/Release/monaco.ipk
    rm -f "$ipk"

    make "monaco-ipk" || exit
fi

ls -sh "$ipk" || exit

ar t >/dev/null "$ipk" || exit

echo Remount...
adb shell mount -oremount,rw /opt/Bose || exit

echo Copy...
adb push "$ipk" /tmp/new-monaco.ipk || exit

echo Install...
adb shell export LD_LIBRARY_PATH=/opt/Bose/update/opkg/ \&\& /opt/Bose/update/opkg/opkg -f /mnt/nv/update/opkg.conf  --add-arch armv7a-vfp-neon:100 --force-reinstall --force-downgrade install /tmp/new-monaco.ipk || exit

echo Remount...
adb shell mount -oremount,ro /opt/Bose || exit

echo Done
