#!/bin/bash
#
# Install Monaco IPK from the .ipk file provided as an argument
# or from a newly created .ipk if none is specified.
#
this=${0##*/}

if (( $# > 1 )); then
    echo >&2 "usage: $this [monaco.ipk]"
    exit 1
fi

if (( $# == 1 )) && [[ "$1" = *.ipk ]]; then
    ipk=$1
else
    cd "$(dirname "$0")/.." || exit
    ipk=$PWD/builds/Release/monaco.ipk
    rm -f "$ipk"

    make "monaco-ipk" || exit
fi

ls -sh "$ipk" || exit

ar t >/dev/null "$ipk" || exit

echo Remount...
adb shell mount -oremount,rw /opt/Bose || exit

echo Uninstall...
adb shell opkg remove --force-remove monaco  # ok if this fails

echo Copy...
adb push "$ipk" /tmp/new-monaco.ipk || exit

echo Install...
adb shell opkg -d bose install /tmp/new-monaco.ipk || exit

echo Remount...
adb shell mount -oremount,ro /opt/Bose || exit

echo Done
