#!/bin/bash
#
# Validates input string as valid version
#
# only numeric values allowed in version
# valid version 1.12, 12.1, 12.12 [Major.Minor]
#               1.1.1, 1.12.1, 12.1.1, 1.1.12, 12.12.1, 1.12.12 [Major.Minor.Patch]
#               1.1.1.1234, 1.12.12.12 [Major.Minor.Patch.BuildNumber]
#               1.1.1-1234, 122.12.12-12 [Major.Minor.Patch-BuildNumber]
#               1.1.1-1234+abcd123, 122.12.12-12+abcd123 [Major.Minor.Patch-BuildNumber+CommitSHA]
#               1.1.1+abcd123, 122.12.12+abcd123 [Major.Minor.Patch+CommitSHA]

this=${0##*/}

if (( $# != 1 )); then
    echo >&2 "usage: $this version-string"
    exit 1
fi
version=$1; shift

if [[ "$version" =~ ^[0-9]+(\.[0-9]+){1,2}([.-][0-9]+)?([+-]g?[0-9a-f]{7,})?$ ]]; then
    echo "Version string is valid"
    exit 0
fi

echo >&2 "$this: Version string is not valid: \"$version\""
exit 1
