#!/bin/bash
#
# Validates input string as valid version
#
# only numeric values allowed in version
# valid version 1.12, 12.1, 12.12 [Major.Minor]
#               1.1.1, 1.12.1, 12.1.1, 1.1.12, 12.12.1, 1.12.12 [Major.Minor.Patch]
#               1.1.1.1234, 1.12.12.12 [Major.Minor.Patch.BuildNumber]
#               1.1.1-1234, 122.12.12-12 [Major.Minor.Patch-BuildNumber]
#               1.1.1-1234+abcd123, 122.12.12-12+abcd123 [Major.Minor.Patch-BuildNumber+CommitSHA]
#               1.1.1+abcd123, 122.12.12+abcd123 [Major.Minor.Patch+CommitSHA]


this_file=$0
version=$1
shift

if [[ "$version" =~ ^[0-9]+(\.[0-9]+){1,2}([.-]{1}[0-9]{1,4}){0,1}(\+[0-9a-zA-Z]{7}){0,1}$ ]]; then 
    echo "$0: version validation successful"
    exit 0
fi

echo "$0: version validation failed, version : \"$version\""
exit 1
