#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC4

GEN_C_SOURCE=\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/CapSense_Control.c\
	$(GEN_SOURCE_DIR)/CapSense_Processing.c\
	$(GEN_SOURCE_DIR)/CapSense_Structure.c\
	$(GEN_SOURCE_DIR)/CapSense_Tuner.c\
	$(GEN_SOURCE_DIR)/CapSense_Filter.c\
	$(GEN_SOURCE_DIR)/CapSense_Sensing.c\
	$(GEN_SOURCE_DIR)/CapSense_INT.c\
	$(GEN_SOURCE_DIR)/CapSense_SensingCSD_LL.c\
	$(GEN_SOURCE_DIR)/CapSense_Centroid_LL.c\
	$(GEN_SOURCE_DIR)/CapSense_ISR.c\
	$(GEN_SOURCE_DIR)/CyFlash.c\
	$(GEN_SOURCE_DIR)/CyLib.c\
	$(GEN_SOURCE_DIR)/cyPm.c\
	$(GEN_SOURCE_DIR)/cyutils.c\
	$(GEN_SOURCE_DIR)/CyLFClk.c\
	$(GEN_SOURCE_DIR)/Blank.c\
	$(GEN_SOURCE_DIR)/Blank_PM.c\
	$(GEN_SOURCE_DIR)/SPIM.c\
	$(GEN_SOURCE_DIR)/SPIM_SPI_UART.c\
	$(GEN_SOURCE_DIR)/SPIM_PM.c\
	$(GEN_SOURCE_DIR)/SPIM_SPI.c\
	$(GEN_SOURCE_DIR)/SPIM_BOOT.c\
	$(GEN_SOURCE_DIR)/SPIM_SPI_BOOT.c\
	$(GEN_SOURCE_DIR)/SPIM_SPI_UART_INT.c\
	$(GEN_SOURCE_DIR)/SPIM_SCBCLK.c\
	$(GEN_SOURCE_DIR)/SPIM_sclk_m.c\
	$(GEN_SOURCE_DIR)/SPIM_sclk_m_PM.c\
	$(GEN_SOURCE_DIR)/SPIM_mosi_m.c\
	$(GEN_SOURCE_DIR)/SPIM_mosi_m_PM.c\
	$(GEN_SOURCE_DIR)/Latch.c\
	$(GEN_SOURCE_DIR)/Latch_PM.c\
	$(GEN_SOURCE_DIR)/SPIM_SCB_IRQ.c\
	$(GEN_SOURCE_DIR)/UART_1.c\
	$(GEN_SOURCE_DIR)/UART_1_SPI_UART.c\
	$(GEN_SOURCE_DIR)/UART_1_SPI_UART_INT.c\
	$(GEN_SOURCE_DIR)/UART_1_PM.c\
	$(GEN_SOURCE_DIR)/UART_1_UART.c\
	$(GEN_SOURCE_DIR)/UART_1_BOOT.c\
	$(GEN_SOURCE_DIR)/UART_1_UART_BOOT.c\
	$(GEN_SOURCE_DIR)/UART_1_SCBCLK.c\
	$(GEN_SOURCE_DIR)/UART_1_tx.c\
	$(GEN_SOURCE_DIR)/UART_1_tx_PM.c\
	$(GEN_SOURCE_DIR)/UART_1_rx.c\
	$(GEN_SOURCE_DIR)/UART_1_rx_PM.c\
	$(GEN_SOURCE_DIR)/UART_1_SCB_IRQ.c

GEN_ASM_SOURCE=\
	$(GEN_SOURCE_DIR)/CyBootAsmGnu.s

GEN_SEP_C_SOURCE=\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/Cm0plusStart.c

GEN_LIBS=\
	Export/ARM_GCC_Generic/CapSense_P4_v3_10/Capsense_P4Library_GCCp.a
