SET(CPACK_PACKAGE_NAME "Professor")
SET(CPACK_PACKAGE_VERSION "1.0") # TBD when we figure out a versioning plan make this use it
#SET(CPACK_PACKAGE_VERSION_MAJOR "${MAJOR_VERSION}")
#SET(CPACK_PACKAGE_VERSION_MINOR "${MINOR_VERSION}")
#SET(CPACK_PACKAGE_VERSION_PATCH "${PATCH_VERSION}")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "apq8017") # Is this right?
SET(CPACK_PACKAGE_CONTACT "Bose Corporation")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Professor")
SET(CPACK_DEBIAN_PACKAGE_SECTION "soundtouch")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "required")
SET(CPACK_SET_DESTDIR true)
SET(CPACK_INSTALL_PREFIX "opt/Bose")
#SET(CPACK_STRIP_FILES "VoiceService") # TBD this doesn't seem to work
SET(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
# TBD this is for the control scripts
#SET( CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/CMake/debian/postinst;${CMAKE_CURRENT_SOURCE_DIR}/CMake/debian/prerm;" )
SET(CPACK_GENERATOR "DEB")
INCLUDE(CPack)
